version: '3.8'

services:
  mysql:
    image: vokenboy/mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: superstud
      MYSQL_DATABASE: database
      MYSQL_USER: stud
      MYSQL_PASSWORD: stud
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-init:/docker-entrypoint-initdb.d


  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
    depends_on:
      - mysql

  backend:
    image: vokenboy/backend:latest
    environment:
      DB_HOST: mysql
      DB_USER: stud
      DB_PASSWORD: stud
      DB_NAME: database
    ports:
      - "5000:5000"
    depends_on:
      - mysql

  frontend:
    image: vokenboy/frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - backend
