version: '3'

services:
  frontend:
    build:
      context: ./frontend                  
      dockerfile: Dockerfile              
    ports:
      - "3000:3000"                           
    volumes:
      - ./frontend:/app                   
      - /app/node_modules                  
    depends_on:
      - backend                            
    environment:
      CHOKIDAR_USEPOLLING: "true"          
      WATCHPACK_POLLING: "true" 

  backend:
    build:
      context: ./backend                   
      dockerfile: Dockerfile               
    ports:
      - "5000:5000"                        
    volumes:
      - ./backend:/app                     
      - /app/node_modules                  
    depends_on:
      - mysql                              
    environment:
      NODE_ENV: development                
      CHOKIDAR_USEPOLLING: "true"          
      DB_HOST: mysql                       
      DB_PORT: 3306
      DB_USER: stud                        
      DB_PASSWORD: stud                    
      DB_NAME: database                    
    command: sh -c "npm install && npm rebuild bcrypt --build-from-source && npm run dev"

  mysql:
    image: mysql:5.7                      
    ports:
      - "3307:3307"                       
    environment:
      MYSQL_ROOT_PASSWORD: superstud      
      MYSQL_DATABASE: database            
      MYSQL_USER: stud                    
      MYSQL_PASSWORD: stud                
    volumes:
      - mysql_data:/var/lib/mysql         
      - ./mysql-init:/docker-entrypoint-initdb.d 

  phpmyadmin:
    image: phpmyadmin:latest              
    ports:
      - "8080:80"                         
    depends_on:
      - mysql                             
    environment:
      PMA_HOST: mysql                     
      PMA_USER: root                      
      PMA_PASSWORD: superstud             

volumes:
  mysql_data:
